### ISSUE TITLE
How to generate snapshot or base.snap?

### ISSUE THREAD

**Issue by Davidleeh** [yanxx297/fast-pokeemu#1]
Seems the snapshot is necessary for symbolically exploring the instruction interpreter of Bochs. But how to generate the snapshot? 

Thanks in advance!

**Comment by Davidleeh** [comment]
I figured it out. It is /tmp/kemufuzzer-XXXXXX stuff...

**Comment by smcc** [comment]
I'm glad to hear you figured this out: from your initial question I wasn't completely sure what you were stuck on. Perhaps I can provide a little more context in case it's helpful for anyone else who finds themselves with similar questions.

You may have noticed that one snapshot with the name base.snap is included in the repository, since it saves some steps to have it available from the beginning. But it can be useful to know how to regenerate this snapshot, either if you just want to be sure you can reproduce every step, or particular if you have changed the kernel in a way that is relevant to the tests you want to generate.

As you have figured out, we make these snapshots by booting a VM and then dumping its register and memory state right before executing a test. These days we usually use QEMU, though probably the kemufuzzer-patched version of Bochs would work too. The snapshot before executing the instruction is the one that we elsewhere keep with a ".pre" extension. The filename where you want this file to go is passed with the KEMUFUZZER_PRE_STATE environment variable to the patched QEMU, but the file is initially created with a temporary name based on the template "/tmp/kemufuzzer-XXXXXX" and then moved to the requested location with rename(2), so the requested location has to be on the same filesystem as /tmp.

**Comment by Davidleeh** [comment]
Cool! Thanks for the response and information! :)

Also could you please correct my understandings (listed below) regarding fast pokeemu if possible? Thanks a lot!

1) The fast pokeemu only targets for 32-bit x86 instructions, correct? Since it seems that the FuzzBall, which pokeemu relies on for symbolic execution, only supports 32-bit x86 instructions... 
But there are some other tools support 64-bit instructions, e.g. Triton (used by MultiNyx). What are the difficulties in replacing FuzzBall with Triton?

2) The fast pokeemu only targets for verification of VCPU, emulated by QEMU, rather than VCPU supported by hardware-assist virtualization, say VT-x? Given the popularity of hardware-assisted hypervisors in recent data centers, how could fast pokeemu help verify commodity data center hypervisors?

**Comment by smcc** [comment]
Q1: Actually, FuzzBALL now supports x86-64 and ARM-32 in addition to x86-32. It did only support x86-32 back when we did the original PokeEMU work, but that's not actually an important reason why we only did x86-32. It's not always easy to keep things straight when there are multiple levels of emulation or simulation, but for generating test cases from Bochs there is no requirement that the architecture FuzzBALL supports is the same as the architecture being tested. The way we currently use it, Bochs is an interpreter that is emulating an x86-32 guest, and we compile Bochs into a Linux/x86-32 binary for running it under FuzzBALL. But the host and guest architectures don't have to be the same. If you compiled Bochs on an ARM system, you would get an ARM-hosted binary that emulates an x86-32 guest, and you could run FuzzBALL on that too. Earlier in the PokeEMU project we even considered using a source-level symbolic execution system like KLEE on Bochs, and that probably could have worked too: we ended up using FuzzBALL mostly because I knew it better.

Some knowledge about the tested architecture is needed in many other parts of the system as well, like the parts inherited from kemufuzzer, the use of Xed, and the treatment of different kinds of operands in test case generation. None of this is fundamental, but it would be a fair amount of engineering work to target a new architecture for testing (which is part of why we haven't done it yet).

I don't think there would be any fundamental reason you couldn't replace FuzzBALL in PokeEMU with Triton: the functionality needed for test generation is pretty basic symbolic execution that just about any tool should support. Some things might be faster or slower with different tools, and some re-engineering would be needed because Triton and FuzzBALL have different interfaces. But IMO it wouldn't be worth doing this just to support a different emulator host architecture.

Q2: Actually, a more precise way of describing the testing that PokeEMU and Fast PokeEMU do is that we use the automatically-generated test cases to compare the behavior of an emulator to the behavior of hardware-virtualization-based VCPU: for instance, comparing QEMU's emulation with KVM. Bugs in either the software emulator or the hardware-based VM would show up as differences in the test outputs, so in theory this comparison could inform you about bugs in either one. But in practice hardware-based VCPUs tend to have many fewer instruction semantics bugs, because most instructions execute directly using the same hardware as non-virtualized execution. Perhaps the most natural target for (Fast) PokeEMU related to hardware virtualization would be the fallback emulator that systems like KVM use in special cases when hardware virtualization isn't possible. Amit et al. (SOSP 2015) tested this part of KVM, and at the time they found a lot of bugs, though perhaps there wouldn't be as many now that all the ones they found were fixed.

**Comment by Davidleeh** [comment]
Sounds good! Thanks a lot for the explanation!! :)
